# Generated by Django 4.2.6 on 2023-11-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mxz_userinfo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mxzuser",
            name="token",
        ),
    ]
