# Generated by Django 4.2.6 on 2023-10-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mxzuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='mxzuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='mxzuser',
            name='photo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='头像'),
        ),
    ]
