# Generated by Django 4.2.6 on 2023-10-24 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeimprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateevent',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='dateevent',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='dateevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='dateevent',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='dateevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
