# Generated by Django 4.2.6 on 2023-10-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_mxzuser_nickname_mxzuser_phone_mxzuser_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mxzuser',
            options={'permissions': (['check_mxzuser', '审核用户信息'],), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
