# Generated by Django 4.2.6 on 2023-10-19 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='事件Id')),
                ('event_content', models.TextField(verbose_name='事件内容')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='开始日期')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='结束日期')),
                ('start_time', models.TimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
